System.config({
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  "paths": {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo:*": "jspm_packages/kendo/*",
    "kendo.*": "jspm_packages/kendo/bower-kendo-ui@2016.1.226+SP1/js/kendo.*.js"
  },
  "meta": {
    "bootstrap": {
      "deps": [
        "jquery"
      ]
    }
  },
  "map": {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.2.1",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.2.5",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.4",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.1",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@0.9.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.2",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.1",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.1",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.4",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.2",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.4",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.6",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.1",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "core-js": "npm:core-js@1.2.6",
    "css": "github:systemjs/plugin-css@0.1.21",
    "fetch": "github:github/fetch@0.11.1",
    "font-awesome": "npm:font-awesome@4.6.1",
    "jquery": "npm:jquery@2.2.3",
    "kendo-ui": "kendo:bower-kendo-ui@2016.1.226+SP1",
    "text": "github:systemjs/plugin-text@0.0.3",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "npm:jquery@2.2.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-animator-css@1.0.0-beta.1.2.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-binding@1.0.0-beta.1.3.5": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.4",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.1",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.4",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.4",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.6",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-framework@1.0.0-beta.1.2.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.5",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.2.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-kendoui-bridge@0.9.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.5",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.6",
      "jquery": "github:components/jquery@2.2.1"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.2.2": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-loader@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.2.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.2.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.2.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-polyfills@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-router@1.0.0-beta.1.2.2": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.2.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.2.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.5",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.2.6": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.5",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.2.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.2",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.7"
    },
    "npm:aurelia-templating@1.0.0-beta.1.2.7": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.5",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:font-awesome@4.6.1": {
      "css": "github:systemjs/plugin-css@0.1.21"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  },
  "bundles": {
    "aurelia": [
      "github:twbs/bootstrap@3.3.6",
      "github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-text@0.0.3",
      "github:twbs/bootstrap@3.3.6/js/bootstrap",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.1",
      "npm:aurelia-animator-css@1.0.0-beta.1.2.1/aurelia-animator-css",
      "npm:aurelia-binding@1.0.0-beta.1.3.5",
      "npm:aurelia-binding@1.0.0-beta.1.3.5/aurelia-binding",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1/aurelia-bootstrapper",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1/aurelia-event-aggregator",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.5",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.5/aurelia-fetch-client",
      "npm:aurelia-framework@1.0.0-beta.1.2.4",
      "npm:aurelia-framework@1.0.0-beta.1.2.4/aurelia-framework",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.1",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.1/aurelia-history-browser",
      "npm:aurelia-history@1.0.0-beta.1.2.1",
      "npm:aurelia-history@1.0.0-beta.1.2.1/aurelia-history",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.2",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.2/aurelia-loader-default",
      "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "npm:aurelia-loader@1.0.0-beta.1.2.0/aurelia-loader",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.1",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.1/aurelia-logging-console",
      "npm:aurelia-logging@1.0.0-beta.1.2.1",
      "npm:aurelia-logging@1.0.0-beta.1.2.1/aurelia-logging",
      "npm:aurelia-metadata@1.0.0-beta.1.2.1",
      "npm:aurelia-metadata@1.0.0-beta.1.2.1/aurelia-metadata",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.1",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.1/aurelia-pal-browser",
      "npm:aurelia-pal@1.0.0-beta.1.2.2",
      "npm:aurelia-pal@1.0.0-beta.1.2.2/aurelia-pal",
      "npm:aurelia-path@1.0.0-beta.1.2.2",
      "npm:aurelia-path@1.0.0-beta.1.2.2/aurelia-path",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.4",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.4/aurelia-polyfills",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.1/aurelia-route-recognizer",
      "npm:aurelia-router@1.0.0-beta.1.2.2",
      "npm:aurelia-router@1.0.0-beta.1.2.2/aurelia-router",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.1/aurelia-task-queue",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.4",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.4/aurelia-templating-binding",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/abstract-repeater",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/analyze-view-factory",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/array-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/aurelia-templating-resources",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/binding-mode-behaviors",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/binding-signaler",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/compile-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/compose",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/css-resource",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/debounce-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/dynamic-element",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/focus",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/hide",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/html-resource-plugin",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/html-sanitizer",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/if",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/map-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/null-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/number-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/repeat",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/repeat-strategy-locator",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/repeat-utilities",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/replaceable",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/sanitize-html",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/set-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/show",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/signal-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/throttle-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/update-trigger-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/view-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.6/with",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/aurelia-templating-router",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/route-href",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/route-loader",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.1/router-view",
      "npm:aurelia-templating@1.0.0-beta.1.2.7",
      "npm:aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating",
      "npm:jquery@2.2.3",
      "npm:jquery@2.2.3/dist/jquery"
    ],
    "kendo-build": [
      "kendo.aspnetmvc.min",
      "kendo.autocomplete.min",
      "kendo.binder.min",
      "kendo.button.min",
      "kendo.calendar.min",
      "kendo.color.min",
      "kendo.colorpicker.min",
      "kendo.columnmenu.min",
      "kendo.columnsorter.min",
      "kendo.combobox.min",
      "kendo.core.min",
      "kendo.data.min",
      "kendo.data.odata.min",
      "kendo.data.signalr.min",
      "kendo.data.xml.min",
      "kendo.dataviz.barcode.min",
      "kendo.dataviz.chart.funnel.min",
      "kendo.dataviz.chart.min",
      "kendo.dataviz.chart.polar.min",
      "kendo.dataviz.core.min",
      "kendo.dataviz.diagram.min",
      "kendo.dataviz.gauge.min",
      "kendo.dataviz.map.min",
      "kendo.dataviz.qrcode.min",
      "kendo.dataviz.sparkline.min",
      "kendo.dataviz.stock.min",
      "kendo.dataviz.themes.min",
      "kendo.dataviz.treemap.min",
      "kendo.datepicker.min",
      "kendo.datetimepicker.min",
      "kendo.dom.min",
      "kendo.draganddrop.min",
      "kendo.drawing.min",
      "kendo.dropdownlist.min",
      "kendo.editable.min",
      "kendo.editor.min",
      "kendo.excel.min",
      "kendo.filebrowser.min",
      "kendo.filtercell.min",
      "kendo.filtermenu.min",
      "kendo.fx.min",
      "kendo.gantt.list.min",
      "kendo.gantt.min",
      "kendo.gantt.timeline.min",
      "kendo.grid.min",
      "kendo.groupable.min",
      "kendo.imagebrowser.min",
      "kendo.list.min",
      "kendo.listview.min",
      "kendo.maskedtextbox.min",
      "kendo.menu.min",
      "kendo.mobile.actionsheet.min",
      "kendo.mobile.application.min",
      "kendo.mobile.button.min",
      "kendo.mobile.buttongroup.min",
      "kendo.mobile.collapsible.min",
      "kendo.mobile.drawer.min",
      "kendo.mobile.listview.min",
      "kendo.mobile.loader.min",
      "kendo.mobile.modalview.min",
      "kendo.mobile.navbar.min",
      "kendo.mobile.pane.min",
      "kendo.mobile.popover.min",
      "kendo.mobile.scroller.min",
      "kendo.mobile.scrollview.min",
      "kendo.mobile.shim.min",
      "kendo.mobile.splitview.min",
      "kendo.mobile.switch.min",
      "kendo.mobile.tabstrip.min",
      "kendo.mobile.view.min",
      "kendo.multiselect.min",
      "kendo.notification.min",
      "kendo.numerictextbox.min",
      "kendo.ooxml.min",
      "kendo.pager.min",
      "kendo.panelbar.min",
      "kendo.pdf.min",
      "kendo.pivot.configurator.min",
      "kendo.pivot.fieldmenu.min",
      "kendo.pivotgrid.min",
      "kendo.popup.min",
      "kendo.progressbar.min",
      "kendo.reorderable.min",
      "kendo.resizable.min",
      "kendo.responsivepanel.min",
      "kendo.router.min",
      "kendo.scheduler.agendaview.min",
      "kendo.scheduler.dayview.min",
      "kendo.scheduler.min",
      "kendo.scheduler.monthview.min",
      "kendo.scheduler.recurrence.min",
      "kendo.scheduler.timelineview.min",
      "kendo.scheduler.view.min",
      "kendo.selectable.min",
      "kendo.slider.min",
      "kendo.sortable.min",
      "kendo.splitter.min",
      "kendo.tabstrip.min",
      "kendo.timepicker.min",
      "kendo.timezones.min",
      "kendo.toolbar.min",
      "kendo.tooltip.min",
      "kendo.touch.min",
      "kendo.treelist.min",
      "kendo.treeview.draganddrop.min",
      "kendo.treeview.min",
      "kendo.upload.min",
      "kendo.userevents.min",
      "kendo.validator.min",
      "kendo.view.min",
      "kendo.virtuallist.min",
      "kendo.webcomponents.min",
      "kendo.window.min",
      "kendo:bower-kendo-ui@2016.1.226+SP1/js/jszip.min",
      "kendo:bower-kendo-ui@2016.1.226+SP1/js/pako_deflate.min",
      "kendo:bower-kendo-ui@2016.1.226+SP1/styles/kendo.bootstrap.min.css!github:systemjs/plugin-text@0.0.3",
      "kendo:bower-kendo-ui@2016.1.226+SP1/styles/kendo.common.min.css!github:systemjs/plugin-text@0.0.3",
      "npm:jquery@2.2.3",
      "npm:jquery@2.2.3/dist/jquery"
    ],
    "app-build": [
      "app",
      "app.html!github:systemjs/plugin-text@0.0.3",
      "blur-image",
      "child-router",
      "child-router.html!github:systemjs/plugin-text@0.0.3",
      "github:systemjs/plugin-css@0.1.21",
      "github:systemjs/plugin-css@0.1.21/css",
      "main",
      "nav-bar.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0",
      "npm:aurelia-kendoui-bridge@0.9.0/autocomplete/autocomplete",
      "npm:aurelia-kendoui-bridge@0.9.0/autocomplete/autocomplete.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/barcode/barcode",
      "npm:aurelia-kendoui-bridge@0.9.0/button/button",
      "npm:aurelia-kendoui-bridge@0.9.0/buttongroup/buttongroup",
      "npm:aurelia-kendoui-bridge@0.9.0/calendar/calendar",
      "npm:aurelia-kendoui-bridge@0.9.0/calendar/calendar.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/chart",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/chart.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/sparkline",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/sparkline.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/stock",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/stock.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/treemap",
      "npm:aurelia-kendoui-bridge@0.9.0/chart/treemap.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/colorpalette/colorpalette",
      "npm:aurelia-kendoui-bridge@0.9.0/colorpalette/colorpalette.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/colorpicker/colorpicker",
      "npm:aurelia-kendoui-bridge@0.9.0/combobox/combobox",
      "npm:aurelia-kendoui-bridge@0.9.0/combobox/combobox.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/common/bindables",
      "npm:aurelia-kendoui-bridge@0.9.0/common/constants",
      "npm:aurelia-kendoui-bridge@0.9.0/common/control-properties",
      "npm:aurelia-kendoui-bridge@0.9.0/common/decorators",
      "npm:aurelia-kendoui-bridge@0.9.0/common/options-builder",
      "npm:aurelia-kendoui-bridge@0.9.0/common/template",
      "npm:aurelia-kendoui-bridge@0.9.0/common/template-compiler",
      "npm:aurelia-kendoui-bridge@0.9.0/common/template-gatherer",
      "npm:aurelia-kendoui-bridge@0.9.0/common/util",
      "npm:aurelia-kendoui-bridge@0.9.0/common/widget-base",
      "npm:aurelia-kendoui-bridge@0.9.0/config-builder",
      "npm:aurelia-kendoui-bridge@0.9.0/contextmenu/contextmenu",
      "npm:aurelia-kendoui-bridge@0.9.0/datepicker/datepicker",
      "npm:aurelia-kendoui-bridge@0.9.0/datetimepicker/datetimepicker",
      "npm:aurelia-kendoui-bridge@0.9.0/diagram/diagram",
      "npm:aurelia-kendoui-bridge@0.9.0/diagram/diagram.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/draggable/draggable",
      "npm:aurelia-kendoui-bridge@0.9.0/drop-target/drop-target",
      "npm:aurelia-kendoui-bridge@0.9.0/drop-target/drop-target-area",
      "npm:aurelia-kendoui-bridge@0.9.0/dropdownlist/dropdownlist",
      "npm:aurelia-kendoui-bridge@0.9.0/dropdownlist/dropdownlist.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/editor/editor",
      "npm:aurelia-kendoui-bridge@0.9.0/flatcolorpicker/flatcolorpicker",
      "npm:aurelia-kendoui-bridge@0.9.0/flatcolorpicker/flatcolorpicker.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/gantt/gantt",
      "npm:aurelia-kendoui-bridge@0.9.0/gantt/gantt-col",
      "npm:aurelia-kendoui-bridge@0.9.0/gantt/gantt-col.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/gantt/gantt.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/gauges/linear-gauge",
      "npm:aurelia-kendoui-bridge@0.9.0/gauges/linear-gauge.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/gauges/radial-gauge",
      "npm:aurelia-kendoui-bridge@0.9.0/gauges/radial-gauge.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/grid/col",
      "npm:aurelia-kendoui-bridge@0.9.0/grid/col.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/grid/grid",
      "npm:aurelia-kendoui-bridge@0.9.0/grid/grid-toolbar",
      "npm:aurelia-kendoui-bridge@0.9.0/grid/grid-toolbar.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/grid/grid.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/index",
      "npm:aurelia-kendoui-bridge@0.9.0/listview/listview",
      "npm:aurelia-kendoui-bridge@0.9.0/listview/listview.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/map/map",
      "npm:aurelia-kendoui-bridge@0.9.0/map/map.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/maskedtextbox/maskedtextbox",
      "npm:aurelia-kendoui-bridge@0.9.0/menu/menu",
      "npm:aurelia-kendoui-bridge@0.9.0/multiselect/multiselect",
      "npm:aurelia-kendoui-bridge@0.9.0/multiselect/multiselect.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/notification/notification",
      "npm:aurelia-kendoui-bridge@0.9.0/notification/notification-template",
      "npm:aurelia-kendoui-bridge@0.9.0/notification/notification.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/numerictextbox/numerictextbox",
      "npm:aurelia-kendoui-bridge@0.9.0/panelbar/panelbar",
      "npm:aurelia-kendoui-bridge@0.9.0/panelbar/panelbar.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/pdf/pdf",
      "npm:aurelia-kendoui-bridge@0.9.0/pivotgrid/pivotconfigurator",
      "npm:aurelia-kendoui-bridge@0.9.0/pivotgrid/pivotconfigurator.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/pivotgrid/pivotgrid",
      "npm:aurelia-kendoui-bridge@0.9.0/pivotgrid/pivotgrid.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/progressbar/progressbar",
      "npm:aurelia-kendoui-bridge@0.9.0/qrcode/qrcode",
      "npm:aurelia-kendoui-bridge@0.9.0/rangeslider/rangeslider",
      "npm:aurelia-kendoui-bridge@0.9.0/rangeslider/rangeslider.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/responsivepanel/responsivepanel",
      "npm:aurelia-kendoui-bridge@0.9.0/scheduler/scheduler",
      "npm:aurelia-kendoui-bridge@0.9.0/scheduler/scheduler.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/scrollview/scrollview",
      "npm:aurelia-kendoui-bridge@0.9.0/scrollview/scrollview.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/slider/slider",
      "npm:aurelia-kendoui-bridge@0.9.0/sortable/sortable",
      "npm:aurelia-kendoui-bridge@0.9.0/splitter/splitter",
      "npm:aurelia-kendoui-bridge@0.9.0/spreadsheet/spreadsheet",
      "npm:aurelia-kendoui-bridge@0.9.0/spreadsheet/spreadsheet.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/switch/switch",
      "npm:aurelia-kendoui-bridge@0.9.0/tabstrip/tabstrip",
      "npm:aurelia-kendoui-bridge@0.9.0/timepicker/timepicker",
      "npm:aurelia-kendoui-bridge@0.9.0/toolbar/toolbar",
      "npm:aurelia-kendoui-bridge@0.9.0/toolbar/toolbar-item",
      "npm:aurelia-kendoui-bridge@0.9.0/toolbar/toolbar-item-button",
      "npm:aurelia-kendoui-bridge@0.9.0/toolbar/toolbar-item-button.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/toolbar/toolbar-item.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/toolbar/toolbar.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/tooltip/tooltip",
      "npm:aurelia-kendoui-bridge@0.9.0/treelist/tree-col",
      "npm:aurelia-kendoui-bridge@0.9.0/treelist/tree-col.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/treelist/treelist",
      "npm:aurelia-kendoui-bridge@0.9.0/treelist/treelist.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/treeview/treeview",
      "npm:aurelia-kendoui-bridge@0.9.0/upload/upload",
      "npm:aurelia-kendoui-bridge@0.9.0/upload/upload.html!github:systemjs/plugin-text@0.0.3",
      "npm:aurelia-kendoui-bridge@0.9.0/validator/validator",
      "npm:aurelia-kendoui-bridge@0.9.0/valueconverters/valueconverters",
      "npm:aurelia-kendoui-bridge@0.9.0/window/window",
      "users",
      "users.html!github:systemjs/plugin-text@0.0.3",
      "welcome",
      "welcome.html!github:systemjs/plugin-text@0.0.3"
    ]
  }
})